### ISSUE TITLE
PGDATA Variable

### ISSUE THREAD

**Issue by dominijk** [postgis/docker-postgis#129]
Is PGDATA environment variable supported? It doesn't seem to pick up my existing db where these are stored in `/usr/local/var/postgres`

**Comment by ImreSamu** [comment]
imho: supported;

my suggestions:  
- check the server logs  
   *  " wrong ownership"?  -> https://github.com/appropriate/docker-postgis/issues/89
- check the upstream issues :  https://github.com/docker-library/postgres/search?q=PGDATA&type=Issues

**Comment by phillipross** [comment]
If this is still an issue, please try with the official PostgreSQL images and see if they work as you are expecting.  If it works with those but doesn't work with the PostGIS images then we can try to troubleshoot from there.

For now I'll leave this issue open, but we'll consider it inactive until you respond and can test the PostgreSQL images.
