### ISSUE TITLE
location of pg_config

### ISSUE THREAD

**Issue by Tjorriemorrie** [postgis/docker-postgis#132]
Hi, where is the location of pg_config on the image?

**Comment by tourdownunder** [comment]
This may going to depend on the distribution. In my 11-2.5/alpine/ I could run docker with a bash entry point and find where it is following the below. 

```
docker run --name test-postgis -p 5430:5432 --entrypoint /bin/bash -it mdillon/postgis:11-alpine 
```

Once inside the container's bash

```
find / -name pg_config 
```

output

```
/usr/local/bin/pg_config
```

**Comment by phillipross** [comment]
For debian images: /usr/bin
For alpine images: /usr/local/bin

Here's some output illustrating running find command in containers using the images:
```
$ for TAG in 11 11-alpine; do echo -n "tag ${TAG} --> "; docker container run --rm -it mdillon/postgis:${TAG} find / -name "pg_config" -print; done
tag 11 --> /usr/bin/pg_config
tag 11-alpine --> /usr/local/bin/pg_config
```

Hope that helps!
