### ISSUE TITLE
Build for the latest PG 11.3 as additionnal packages for 11.2 are missing

### ISSUE THREAD

**Issue by rdavaillaud** [postgis/docker-postgis#133]
Hello,
the docker image is 2 months olds, still pointing to PG 11.2-1, but some debian packages on the repository are upgraded to 11.3.

Is it possible to build the images for the latest release of Postgres 11 or make the build automatic?

Thanks

**Comment by tourdownunder** [comment]
I had the same issue which I assume is docker hub caching.

I just added the .3 in the Dockerfile to be explicit in the from statement on my fork https://github.com/tourdownunder/docker-postgis/tree/fixup/pg-11.3

You can build and run after cloning using something like
```
docker build -t alpine-pg11-postgis2.5 -f 11-2.5/alpine/Dockerfile 
export MOUNT_DATA_PATH=~/Documents/postgresql-11/data
docker run -p 5433:5432 -v $MOUNT_DATA_PATH:/var/lib/postgresql/data alpine-pg11-postgis2.5
```

**Comment by rdavaillaud** [comment]
It turns out that you just have to rebuild the image, as the Postgres 11 tag is the latest, and is the same as 11.3.

**Comment by tourdownunder** [comment]
You can close this issue if its no longer a problem for you.

**Comment by rdavaillaud** [comment]
It's still an issue as the "official" build is not up to date.

**Comment by frafra** [comment]
It would be better to add tags for minor releases too, like you did for the 9.x releases.

**Comment by phillipross** [comment]
Builds are coming for new updated official images.  Currently PR #166 is in-progress, and we aim to have updated/current images in docker hub soon, so I'll close this issue.  Thanks for the patience 😉
