### ISSUE TITLE
Keep it up to date

### ISSUE THREAD

**Issue by murbanowicz** [postgis/docker-postgis#139]
Hi,

Thank you for these images.
Could we think about some webhook or something like that to update these images on new releases of Postgres images? It would be really beneficial as we would stop missing security updates etc.

**Comment by braderhart** [comment]
@murbanowicz Maybe try to reach out to @md5 directly from the email on his profile. I'm using skaffold currently which helps improve the build process, but I'm not of a fan of giving Docker access to my account. A simple cron job would even do the trick:

https://hub.docker.com/r/equalos/postgis

Also would be nice to have a version to match RDS. RDS is on PostGIS version 2.5.1 and PostgreSQL 11.4.

**Comment by md5** [comment]
I'm not going to do anything with this image until #143 is resolved, unfortunately

**Comment by ankurk91** [comment]
found this 
https://github.com/GUI/postgis-docker

They have automate this build and push process through GitHub actions.

**Comment by phillipross** [comment]
You can keep an eye on PR #166 which is currently in progress and will be the start of an effort to maintain official images that are supported and current.  Automation will definitely be part of this effort.  Thanks for being patient!
