### ISSUE TITLE
Discussion: Move to docker-postgis/postgis on Docker Hub, new maintainers needed

### ISSUE THREAD

**Issue by md5** [postgis/docker-postgis#143]
Hi all. I'm opening this issue to discuss future maintainership of this image.

As those who have used the image for a while and have followed this repository should know, I have long been reluctant to continue maintaining this image since I do not use it myself and only ever barely used it when it was first created. I'm not going to dig up every link to every discussion on this topic, but it has been thoroughly gone over in the issue history.

The main reasons I have always been hesitant to simply abandon this image are:

1. People use it and I don't want to break their stuff
2. Docker Hub does not support image redirects (still, right?), so I can't move the image to another name without triggering `#1`
3. The Docker Hub ecosystem does not have a way for me to tell users that the image is moving to a new (more community-maintained) name
4. I don't want to stay involved enough to want work to continue under the `@appropriate` organization (despite the fact that the image is in my personal `mdillon/*` namespace and Appropriate Computing LLC no longer exists as a legal entity)

I found out reason `#2` the hard way when I tried to move the image from `mdillon/postgis` to `appropriate/postgis`. This broke the Docker Hub to GitHub integration in a way that I don't think ever fully recovered.

Given that my neglect of this image has probably already led to breakage (sorry), I think it's time to finally break through the issues above and move this image, both on Docker Hub and on GitHub.

I would appreciate any thoughts from long-time users (@ImreSamu comes to mind).

**Comment by jingsam** [comment]
We use `mdillon/postgis` in our production deploy. Thanks for your great work  @md5. I suggest to choose a easy to remember name if move this image, as sometimes I mistyped `mdllion`, `mdilon`. Sorry for that 😂. It would be better if we can contribute this repo to postgis group to  be an offical postgis docker image.

I would like to be an volunteer maintainer of this repo.

**Comment by murbanowicz** [comment]
I can also try to help with that.
Using this opportunity we could also do something to keep it up to date like I mentioned in #139

**Comment by tdamsma** [comment]
I completely understand you not willing to put effort in this repo if you don't use it yourself. Thanks for the work! I think it would be best if the postgis team would be willing to adopt this image. I looked if I can file an issue for that, but the bugtracker they use is not so accessible. Is anyone from the postgis team watching this, or can anyone notify them?

**Comment by md5** [comment]
@tdamsma it looks like there is an active `postgis` namespace on Docker Hub being used as part of a CI pipeline: https://hub.docker.com/u/postgis

**Comment by ImreSamu** [comment]
Thank you for your work!
Any solution is OK for me;   Welcome change!   

My personal preference: collaborating one of the upstream projects  ( [postgis](https://hub.docker.com/u/postgis)  and/or  [docker-library](https://github.com/docker-library) )   and using their automatization / infrastructure / best practices / ...

**Comment by md5** [comment]
@ImreSamu given that the Postgres project still isn't involved in the `postgres` image itself, it's probably a stretch to hope that someone from PGDG or some other part of the Postgres community will take an interest in adopting this image.

To be honest, you hit on one of the biggest parts of maintaining this image that has been a pain, which is the lack of reliable automation. If this were an image that I had been using myself, I might have been more willing to foot the bill for some of that automation myself. Instead, I have done the best I thought was reasonable given both my availability and the free infrastructure options I have been aware of.

**Comment by SlothOfAnarchy** [comment]
First of all, thanks for maintaining this image so far @md5 !

> To be honest, you hit on one of the biggest parts of maintaining this image that has been a pain, which is the lack of reliable automation. If this were an image that I had been using myself, I might have been more willing to foot the bill for some of that automation myself. Instead, I have done the best I thought was reasonable given both my availability and the free infrastructure options I have been aware of.

There is an easy way that I have implemented myself recently: You can generate a URL on Docker hub which triggers a build (Builds -> Configure Builds -> Build Triggers). I see you are already using travis CI - you can add a [curl request](https://github.com/trump-fmi/area-server/blob/master/.travis.yml#L10) that calls this URL in one of the install phases. Then you just have to enable weekly travis builds for this repo and it should work.
I deployed this on a University project, but I think all of those steps can be accomplished for free if the repo is public.

**Comment by robe2** [comment]
I've ticketed in our issue system - https://trac.osgeo.org/postgis/ticket/4548

I don't expect to be much traction until after PostGIS 3.0.0 is released next week.

**Comment by md5** [comment]
Thanks @robe2!

**Comment by phillipross** [comment]
@md5 Are you looking to transfer this repo to the postgis org?  I believe your issue #2 is taken care of if you transfer the repo across organizations as long as you don't fork the repo back into your own namespace.  I've been watching this issue for almost 6 months and haven't seen much traction, so I'm attempting to initiate some progress in establishing some kind of handoff and work through whatever issues there might be.

**Comment by nyurik** [comment]
@md5 I agree - I think if you simply transfer repo's ownership to postgis organization, all the existing URLs will continue working, simply redirecting to the new org, plus issues, PRs, etc will all work as before.  If you really want, you could fork it under a different name I think, to avoid breaking URLs (I think that's possible, but not sure if it could be done automatically)

**Comment by md5** [comment]
If someone from the @postgis org can make that happen, I'm happy to transfer the project

**Comment by dbaston** [comment]
@md5 looks to me like you should be able to initiate the transfer to the postgis org: https://help.github.com/en/github/administering-a-repository/transferring-a-repository#transferring-a-repository-owned-by-your-organization

**Comment by phillipross** [comment]
@md5 Thanks, I'm coordinating with folks to make this happen.

@dbaston The article you referred to is the short and more straightforward one, but requires @md5 to have permissions within the postgis organization to create repos.  There is a separate article that illustrates setting up the transfer in a way that doesn't require granting permissions directly within the organization.  It's slightly more complicated in that involves setting up an intermediate repo or something that acts as a handoff point, but I'll dig up the article for that and put it here.  I'm only a member of the postgis org on github, not an owner, and I think they've set up permissions so that only owners are able to create teams, new repos, etc.  I'll try to coordinate with one of the org owners on irc to see if I can enlist somebody's assistance with that.

Thanks!

**Comment by md5** [comment]
@phillipross that's great news. I think we can do the transfer without an intermediate org if I grant admin privileges to this repo to someone in @postgis who is able to create new repos over there

**Comment by phillipross** [comment]
@md5 I believe that's correct.  I'll just need to find the someone that does have the access and the bandwidth to help.  I'll start pinging folks tomorrow and see who's available to help with the permissions.  Thanks!

**Comment by dbaston** [comment]
I'm happy to be the intermediate (I have the permissions) though I think you have them as well, @phillipross ?

**Comment by md5** [comment]
Thanks @dbaston! I've invited you as an admin on this repo. You can add @phillipross as well if that is helpful to getting things done.

We can continue to discuss the transfer here or in whatever way makes the most sense to the @postgis folks.

**Comment by dbaston** [comment]
And here we are: https://github.com/postgis/docker-postgis
Thanks, @md5!

**Comment by md5** [comment]
Excellent! I don't think getting Travis, etc working will depend on my access. If it does, please let me know 👍🏼

**Comment by nyurik** [comment]
Awesome news!
/me wonders if we would want to rename it to simply "postgis/docker" ?

**Comment by md5** [comment]
@nyurik the drawback of that name is that the recommended `clone` command will name the local directory `docker` in that case. Looking at the other repos in the org, the name change that seems more aligned is `@postgis/postgis-docker`, if anything

**Comment by nyurik** [comment]
Sure, sounds good to me. Thx for looking into it

**Comment by phillipross** [comment]
thanks @dbaston !  the next step is CI

**Comment by phillipross** [comment]
@md5 Do you know if it's possible to move GitterIM room (https://gitter.im/appropriate/docker-postgis) from the appropriate community to the postgis community?

It would be nice to move it to the postgis community rather than having existing people in the room have to signup to a new one.

**Comment by md5** [comment]
Looks like I can email support@gitter.im to request the change: https://gitlab.com/gitlab-org/gitter/webapp/blob/develop/docs/faq.md#what-happens-if-i-rename-something-on-github-org-repo

I can do that tomorrow

**Comment by md5** [comment]
@phillipross I have been told the Gitter room is migrated 😎

**Comment by phillipross** [comment]
Excellent, thank you!  I'll update the links in the README.md files to reflect.

**Comment by clbarnes** [comment]
So where do we pull images from, today? This repo's README says `postgis/postgis`, but that doesn't work. `mdillon/postgis` hasn't been updated in a year. This repo is active: where are its images going?

**Comment by smellman** [comment]
We are still moving new docker repository.
If you need new image soon, please run `make`.

**Comment by md5** [comment]
I contacted Docker Support to see about moving the repo with stars intact. We'll see what they say.

**Comment by phillipross** [comment]
@md5 THAT would be great.  The ideal would be a redirect, but even if they could move it and keep the stats (we love stats), that would be great too.  I'll hold off on pushing any images until they get back to you with some definitive information.  Keep us updated.  Thanks!

**Comment by md5** [comment]
I didn't get a ticket number or anything, so I have no way to follow up or any ETA.

Given that, I would probably continue getting the CI working if I were you, but perhaps push to a temporary name like postgis/postgis-test

**Comment by phillipross** [comment]
@md5 Those are my thoughts exactly.  We've made a few modifications to externalize the repo and image name to facilitate overriding the values via environment vars, but we'll be making a few more to help provide more flexibility for staging/testing images in the CI flows.

Obviously the stats on the existing repo can be an indicator of community confidence and it would be valuable to maintain that trust indicator, so I think it will be fine to wait a few days to see if they get back to you and can help get the docker hub repo transferred. We're not treating it as a blocker though.

Again, thanks for all of your assistance with this!

**Comment by SDenman** [comment]
Guys, really appreciate all your work on this. 
Have been using the mdillon/postgis image for a while but am now building a new project based on postgres 12. 
From the github page, it looks like the integration has been done for this but I understand from above that ongoing image maintenance and ownership might be an issue.
Can someone tell me if there's any way to get hold of an image now that combines postgres 12 and postgis? Or if not when / if that might happen.
Many thanks
Simon.

**Comment by phillipross** [comment]
@SDenman The appropriate/postgis images have been built on top of the official postgresql images, and the transition that is happening now will transfer maintenance of these images to the official postgis project.  The code that is currently in this docker-postgis repo continues to be built on top of the official postgres images and has been updated to produce images for postgres versions 9.5 through 12 which include postgis 2.5 or 3.0 extensions.  The code is relatively simply to build on Linux and MacOS (i'm not sure about windows at the moment) and images will begin publishing to dockerhub repos very soon.

**Comment by SDenman** [comment]
Thanks @phillipross, that's great news. 
Since I'm doing this on MacOS right now, I don't suppose you could point me to some description of the 'relatively simple build process' or is 'very soon' likely to be in the next week? In which case, I may just wait.
Thanks again.

**Comment by phillipross** [comment]
@SDenman We're  currently waiting to see if the dockerhub support can help transfer the appropriate repo to the postgis organization instead of creating a new repo from scratch, so that could be a day, a week, or a month... we're not sure.

More comprehensive documentation is on the way too, but in the meantime, on MacOS, with Docker Desktop for MacOS, you can simply clone the docker-postgis repo and invoke `make` from the root of the repo.  It should build all images for you.  If you want to build a specific image should be able to invoke make and specific a specific directory which corresponds to the version you want (example: `make 12-3.0`) and it should just build the debian and alpine image for that version.  If you have problems with building, you can open an issue against this repo and we'll help you 😉

**Comment by SDenman** [comment]
Brilliant, thanks @phillipross,
I'll have a go at that.

**Comment by phillipross** [comment]
@md5 after looking at the activity on an issue you opened back in the day (and reviewing the references issues) I'm thinking that it might be a lost cause waiting for docker hub to transfer the repo.  What do you think?

**Comment by md5** [comment]
> @md5 after looking at the activity on an issue you opened back in the day (and reviewing the references issues) I'm thinking that it might be a lost cause waiting for docker hub to transfer the repo. What do you think?

You're probably right. There are likely more fruitful ways to get in touch with the right people than the contact form I used, but I don't know what they are.

The question remains of what to do with the old image. If nothing is done, will the existing `mdillon/postgis` still dominate the search results? Right now, the first hit for “postgis” is `postgis/postgis-build-env` with `mdillon/postgis` second. Maybe it just won't be an issue?

**Comment by nyurik** [comment]
I think we should at least update the readme for that image to indicate the new versions will be published under a new name - e.g. put a note in big red letters at the top, saying that `this repo is now published as postgis/postgis-docker`.  From the looks of it, it is possible to change the source of the `mdillon/postgis` autobuild to a different repo, so updating readme in the new repo should reflect in the `mdillon/postgis` too (in theory?).

Note that if @md5 forks the new postgis-hosted github repo into his own namespace, github might delete the redirect to the new postgis, and it won't be possible to restore it later. And we obviously shouldn't delete the older images as people might still be using them.

**Comment by phillipross** [comment]
@md5 I think it's time for the postgis/postgis repo to be created on dockerhub, images to be pushed manually from the most recent postgis-docker repo (which now include pgsql 12 + postgis 3) and the readme on dockerhub to be manually updated.  Then we'll see what happens with the search results

**Comment by phillipross** [comment]
@nyurik I think you're right about the redirects.  After I get the dockerhub repo created and images pushed, then the old image readme can be updated to refer to the new.

**Comment by phillipross** [comment]
closing this issue as resolved 😉
