### ISSUE TITLE
Proj4-dev no longer in Alpine 

### ISSUE THREAD

**Issue by gijoe462** [postgis/docker-postgis#146]
In the docker-postgis/11-2.5/alpine/Dockerfile the build files will no longer build due to-

+ apk add --no-cache --virtual .build-deps-edge --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing --repository http://dl-cdn.alpinelinux.org/alpine/edge/main gdal-dev geos-dev proj4-dev protobuf-c-dev
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  proj4-dev (missing):
    required by: .build-deps-edge-20190814.193155[proj4-dev]

A quick search of Alpine Packages shows it is no longer there.

**Comment by braderhart** [comment]
This has been renamed to `proj-dev`. Checkout https://hub.docker.com/r/equalos/postgis which has a link to the `Dockerfile`.

**Comment by jrzerr** [comment]
@braderhart I pulled that Dockerfile down and it doesn't work with postgres 11.2 and postgis 2.5.2.  postgis configure does not find the new proj libs.  I had to work around it by compiling proj 4.9.3 from source and using --with-projdir in the postgis configure.

**Comment by braderhart** [comment]
@jrzerr This had worked previously, but it looks like someone has flagged the Alpine package likely due to some issues win the latest build that was released on 10/07.

**Comment by phillipross** [comment]
Hi all... I think this issue has since been resolved so I'm going to close it.

FYI: Work is currently being done to get updated versions of both debian and alpine images going.  The master branch contains code to build PostGIS v2.5.3 on alpine for PostgreSQL versions 9.5 through 12.  You can clone, build, and test from there.

**Comment by braderhart** [comment]
Feel free to copy my clean working example here for Alpine:

https://hub.docker.com/r/equalos/postgis
