### ISSUE TITLE
Error relocating /usr/lib/libprotoc.so.20

### ISSUE THREAD

**Issue by GammaGames** [postgis/docker-postgis#147]
I was having problems building the image, getting the following error when it would try to run `make`:

```sh
Error relocating /usr/lib/libprotobuf.so.20: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
Error relocating /usr/lib/libprotoc.so.20: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
make[1]: Leaving directory '/usr/src/postgis/postgis'
make[1]: *** [Makefile:200: vector_tile.pb-c.c] Error 127
make: *** [GNUmakefile:16: all] Error 1
```

I went to the [postgis package](https://pkgs.alpinelinux.org/package/edge/testing/x86_64/postgis) on the alpine repo and saw they had (previously, [removed as of 2019-09-12](https://git.alpinelinux.org/aports/commit/testing/postgis?id=4bb87d996100252810dcc188da164c0c5a7406de)) used a `--without-protobuf` flag when configuring. I changed my `dockerfile` to use the command `./configure --without-protobuf`. That fixed the errors, and the container is now building.

**Comment by GammaGames** [comment]
This is in combination with #146, where I had to use the `proj-dev` package as well

**Comment by GammaGames** [comment]
I was able to use the dockerfile from appropriate/docker-postgis/pull/151 and the psql12-postgis3 dockerfile no longer has this issue.

**Comment by phillipross** [comment]
@GammaGames We're currently working to provide updated images and PR #151 will be a part of this.  Alpine images for PostGIS v2.5.3 on PostgreSQL v9.5 through v12 are currently buildable off of the master branch so you can test those if you'd like, and PostGIS v3.x will be available soon.

I'm going to close this specific issue as it seems you've got workable solutions.
