### ISSUE TITLE
Mixing packages from edge and v3.10 breaks build

### ISSUE THREAD

**Issue by GammaGames** [postgis/docker-postgis#149]
Trying to build the dockerfile located at [11-2.5/alpine/Dockerfile](https://github.com/appropriate/docker-postgis/blob/master/11-2.5/alpine/Dockerfile) (after fixing #146) causes an error while compiling postgis:

```
configure: error: could not find libproj - you may need to specify the directory of a PROJ.4 installation using --with-projdir
```

Proj is currently only available on edge, in the future it might be available on the community tree, but for now installing every dependency from edge fixes the issue.

**Comment by phillipross** [comment]
@GammaGames I believe this issue is outdated too so I'm closing.
