### ISSUE TITLE
ERROR:  function postgis_lib_version() does not exist                 

### ISSUE THREAD

**Issue by SDenman** [postgis/docker-postgis#170]
Hi,
I just built an image for 12-2.5 and integrated it into my project.
The problem comes when I try to add doctrine mappings using https://github.com/jsor/doctrine-postgis
This library (which worked fine with mdillon/postgis) has a function which checks for postgis version 2.x and this makes the following query:
SELECT PostGIS_Lib_Version()
And it's this query that throws the above error stating that the function does not exist.
Any ideas what I might be doing wrong here?

Thanks

**Comment by phillipross** [comment]
@SDenman I'm not familiar with doctrine, but to rule out that something is wrong with the image that you've built, try this:
```
# Start a short-lived container for testing and watch the output until a message
# appears stating that the database system is ready to accept connections:

docker container run --rm --name test-postgis-issue170 -e POSTGRES_PASSWORD=test-postgis-issue170 postgis/postgis:12-2.5

# In a separate terminal, connect to the container and run psql with the query:

docker container exec test-postgis-issue170 psql -U postgres -c "SELECT PostGIS_Lib_Version()"
```

If the output shows a 2.5.x version number, then you can consider your images to be built correctly and turn your attention to doctrine.

**Comment by SDenman** [comment]
My bad, the database hadn't initialised properly. Sorry for wasting your time.

**Comment by phillipross** [comment]
@SDenman no problem... glad you resolved it 😉
