### ISSUE TITLE
10_postgis.sh

### ISSUE THREAD

**Issue by GammaGames** [postgis/docker-postgis#188]
When I build the images from this repo on my machine the `/docker-entrypoint-initdb.d` folder has a `10_postgis.sh` file, which is great because I have some setup scripts I would like to run after the extensions are installed.

When I use a dockerfile with `FROM postgis/postgis:12-3.0` it only has the `postgis.sh` file, which makes me put `pz#` in front of each of my scripts to ensure the execution order. Is this a bug, or expected behavior?

**Comment by ImreSamu** [comment]
> When I use a dockerfile with FROM postgis/postgis:12-3.0 it only has the postgis.sh file

imho:  probably a cache problem.
* try to pull the latest version. `docker pull postgis/postgis:12-3.0`
* or use:  `docker build --pull -t  ...`   for building your images. 
   * ` --pull |  Always attempt to pull a newer version of the image`  ( [doc](https://docs.docker.com/engine/reference/commandline/build/) )

audit log:

```
$ docker pull postgis/postgis:12-3.0
12-3.0: Pulling from postgis/postgis
Digest: sha256:2f06181082f0773fb054ad45d8410799d29c89304421950a01b962ed6a6ae8c8
Status: Image is up to date for postgis/postgis:12-3.0
docker.io/postgis/postgis:12-3.0

$ docker images  | grep postgis
postgis/postgis            12-3.0              2a8383004ab9        3 days ago          490MB

$ docker run -it --rm postgis/postgis:12-3.0 bash -c 'ls /docker-entrypoint-initdb.d/*'
/docker-entrypoint-initdb.d/10_postgis.sh
```

**Comment by GammaGames** [comment]
That was the problem, thank you!
