### ISSUE TITLE
postgres:13 and postgis

### ISSUE THREAD

**Issue by ImreSamu** [postgis/docker-postgis#195]
Postgres 13 beta 1 ( https://www.postgresql.org/about/news/2040/ ) available as a docker image
```
$ docker pull postgres:13
13: Pulling from library/postgres
Digest: sha256:9a1f91d5d531b25699d94d8d311e57b721f6f6a0e5b22fa7c3ecfbb793158297
Status: Image is up to date for postgres:13
docker.io/library/postgres:13
```

what is the planned versions ?
- ~~`13-2.5`~~
- `13-3.0`         waiting for the debian upstream 
- `13-master`   :heavy_check_mark:    ready for test:  `docker pull postgis/postgis:13-master`

EDIT1: removed the 13-2.5 version , based on the feedback
EDIT2: `13-master` is done

**Comment by phillipross** [comment]
https://trac.osgeo.org/postgis/wiki/UsersWikiPostgreSQLPostGIS

If the support matrix is accurate, PostGIS v2.5 isn't supported with Postgres v13.

**Comment by ImreSamu** [comment]
@phillipross : Thanks for the info.

probably some package is missing from the debian repo 
```
E: Unable to locate package postgresql-13-postgis-3
E: Unable to locate package postgresql-13-postgis-3-scripts
```
so I added only the `13-master` ( https://github.com/postgis/docker-postgis/pull/196 )

**Comment by ImreSamu** [comment]
status : waiting for `postgresql-13-postgis-3`
