### ISSUE TITLE
Alpine updates

### ISSUE THREAD

**Issue by jrd** [postgis/docker-postgis#218]
Can you update all -alpine images please?

Upstream seems to use Alpine 3.12 by now and your images uses Alpine 3.9 and the latter does not have all security fixes.

A simple rebuild/push will do.

**Comment by ImreSamu** [comment]
> and your images uses Alpine 3.9

IF you are using the [ old -  `mdillon/postgis` docker hub repo](https://hub.docker.com/r/mdillon/postgis/tags?page=1&ordering=last_updated)   (  like  `mdillon/postgis:9.5-alpine`  images )   (  still Alpine 3.9 - Updated 2 years ago )  
THEN  please update to  the new images --> `postgis/postgis:9.5-2.5-alpine`  and it should work .. 
It is Alpine 3.12 based;
 
* new docker hub repo :  https://registry.hub.docker.com/r/postgis/postgis/tags?page=1&ordering=last_updated

( see the docker hub - transition issue , for the details  : https://github.com/postgis/docker-postgis/issues/143 )


```
$ docker run -it --rm postgis/postgis:9.5-2.5-alpine  bash -c "cat /etc/os-release"
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.12.3
PRETTY_NAME="Alpine Linux v3.12"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"

$ docker run -it --rm postgis/postgis:13-3.1-alpine  bash -c "cat /etc/os-release"
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.12.3
PRETTY_NAME="Alpine Linux v3.12"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"

```

**Comment by jrd** [comment]
Thank you very much, didn’t see the repo transition.
