### ISSUE TITLE
execute custom postgis.sh (migrating from mdillon/postgis)

### ISSUE THREAD

**Issue by domdinicola** [postgis/docker-postgis#232]
is there any way to migrate easily, i tried postgis/postgis but it doesn't load scripts as "docker-entrypoint-initdb.d/postgis.sh"

**Comment by domdinicola** [comment]
I guess it's a new location for the file "/docker-entrypoint-initdb.d/10_postgis.sh"

**Comment by ImreSamu** [comment]
>I guess it's a new location for the file "/docker-entrypoint-initdb.d/10_postgis.sh"

yes, 
```bash
$ docker run -it --rm postgis/postgis:13-3.1-alpine bash -c "ls -la /docker-entrypoint-initdb.d/*"
-rw-r--r--    1 root     root           617 Apr 12 05:39 /docker-entrypoint-initdb.d/10_postgis.sh
```

this is based on the upstream Postgres docker image documentation: 
 *  https://hub.docker.com/_/postgres search -> "Initialization scripts" 
_"If you would like to do additional initialization in an image derived from this one, add one or more *.sql, *.sql.gz, or *.sh scripts under /docker-entrypoint-initdb.d (creating the directory if necessary). After the entrypoint calls initdb to create the default postgres user and database, it will run any *.sql files, run any executable *.sh scripts, and source any non-executable *.sh scripts found in that directory to do further initialization before starting the service.  .... "_
