### ISSUE TITLE
Connection command in README

### ISSUE THREAD

**Issue by amercader** [postgis/docker-postgis#234]
Thanks for this image, it's really helpful to get PostGIS running!

Is there are a reason that the README suggests using another separate postgres container to connect to the postgis one rather than connecting directly using `docker exec`?

ie, using this:

```shell
docker exec -ti some-postgis psql -U postgres
```

instead of this:

```shell
docker run -it --link some-postgis:postgres --rm postgres \
    sh -c 'exec psql -h "$POSTGRES_PORT_5432_TCP_ADDR" -p "$POSTGRES_PORT_5432_TCP_PORT" -U postgres'
```

**Comment by phillipross** [comment]
I can't think of any "good" reason for doing it this way.  I imagine the documentation was simply written so long ago, hasn't been updated, and might have been written this way in older versions of the postgres official image.

**Comment by phillipross** [comment]
@amercader i'm going to close out this issue now, but please feel free to submit a PR documenting a more modern way to make connections.  Thanks!

**Comment by amercader** [comment]
Thanks @phillipross I just did that
