### ISSUE TITLE
include loader/dumper 

### ISSUE THREAD

**Issue by bnordgren** [postgis/docker-postgis#239]
Today I noticed I couldn't find `shp2pgsql` in the postgis/postgis:latest docker file. Other people on gis.stackexchange.org have apparently noticed as well, but their questions have no answers. I assume this is an oversight?

- https://gis.stackexchange.com/questions/384381/shp2pgsql-available-in-postgis13-3-1-alpine-but-no-in-postgis13-3-1-docker-ima?r=SearchResults&s=1|66.0157
- https://gis.stackexchange.com/questions/384181/missing-shp2pgsql-command-on-postgis-docker-installation-when-i-use-postgispos?r=SearchResults&s=3|57.5446

Would it be possible to ensure these are rolled into the docker image?

**Comment by phillipross** [comment]
Hello!  The omission of shp2pgsql from the images is intentional.  Please see #222 and #224 for some explanation and discussion.  Also see the examples directory of the repo for an example of using a extending the images with a custom Dockefile which installs the CLI tools in your own image.
