### ISSUE TITLE
 alpine3.14 + postgis 2.5  + geos 3.9 problems

### ISSUE THREAD

**Issue by ImreSamu** [postgis/docker-postgis#242]
This Monday - the weekly "Docker PostGIS CI"  has been crashed , and I can't fix myself :sad: 
* https://github.com/postgis/docker-postgis/actions/runs/977842899
  * 10-2.5-alpine  - [log](https://github.com/postgis/docker-postgis/runs/2928674145?check_suite_focus=true)
  * 11-2.5-alpine  - [log](https://github.com/postgis/docker-postgis/runs/2928674219?check_suite_focus=true)
  * 12-2.5-alpine -  [log](https://github.com/postgis/docker-postgis/runs/2928674282?check_suite_focus=true)
 
My theory: The [upstream project - `docker-library/postgres` - moved to Alpine 3.14](https://github.com/docker-library/postgres/commits/master) .. and our current code is not working :disappointed: 
 
### Error msg :
```bash
======================================
Now you are ready to run './configure'
======================================
+ pcre-config --prefix
+ ./configure '--with-pcredir=/usr'
configure: error: cannot find required auxiliary files: config.rpath
```

**Comment by phillipross** [comment]
You're right, the weekly CI builds failed last night.  I'll re-run the build again and see if it was a temporary/sporadic thing, and if it continues failing I'll test it by hand.

**Comment by ImreSamu** [comment]
>  I'll re-run the build again and see if it was a temporary/sporadic thing, 

I can replicate in my local environment ...  And I have spent a few hours debugging.
what I know .. these 2 releases not the same :

```bash
wget https://github.com/postgis/postgis/archive/2.5.5.tar.gz
wget https://ftp.osuosl.org/pub/osgeo/download/postgis/source/postgis-2.5.5.tar.gz    #  < -- this is better ; contains the ./configure  command

$ tar -tvf 2.5.5.tar.gz  | grep configure
-rw-rw-r-- root/root     54493 2020-08-15 17:10 postgis-2.5.5/configure.ac
-rw-rw-r-- root/root       522 2020-08-15 17:10 postgis-2.5.5/extras/rpm/patches/postgis-configure.patch

$  tar -tvf postgis-2.5.5.tar.gz  | grep configure
-rw-r--r-- jenkins/jenkins   54493 2020-08-15 20:43 postgis-2.5.5/configure.ac
-rwxr-xr-x jenkins/jenkins  615964 2020-08-15 20:43 postgis-2.5.5/configure   # <---  no need ./autogen.sh ; ./configure is ready
-rw-r--r-- jenkins/jenkins     522 2020-08-15 20:43 postgis-2.5.5/extras/rpm/patches/postgis-configure.patch

```

**Comment by phillipross** [comment]
Thanks @ImreSamu 

I was able to reproduce too.  Looks like all the debian builds are fine but all the alpine builds are broken.  I'm digging into the alpine builds now to track down the problem.

**Comment by ImreSamu** [comment]
@phillipross :

I can't solve it...  :cry: 
my best effort:  https://github.com/postgis/docker-postgis/pull/244
```
Run tests: 128
Failed: 6
make: *** [Makefile:307: check] Error 6
```
