### ISSUE TITLE
#5 4.017 E: Version '3.1.4+dfsg-1.pgdg110+1' for 'postgresql-14-postgis-3' was not found

### ISSUE THREAD

**Issue by tabvn** [postgis/docker-postgis#269]
#5 4.017 E: Version '3.1.4+dfsg-1.pgdg110+1' for 'postgresql-14-postgis-3' was not found

**Comment by amauryval** [comment]
Hello,
Also, I'm getting this error message about postgresql-13

#5 4.210 E: Version '3.1.4+dfsg-1.pgdg110+1' for 'postgresql-13-postgis-3' was not found

**Comment by ImreSamu** [comment]
Thanks for opening this issue!
* in similar cases:  you can update with the `make update`
    * https://github.com/postgis/docker-postgis/blob/master/Makefile#L70-L71
* I have created a PR :  https://github.com/postgis/docker-postgis/pull/270/files

**Comment by ImreSamu** [comment]
@tabvn ; @amauryval 
[The fix PR270](https://github.com/postgis/docker-postgis/pull/270/files)  has been merged to the `master` branch !
Please re-test!

**Comment by amauryval** [comment]
@ImreSamu It's good on my side. Thanks !

**Comment by phillipross** [comment]
once again, many thanks @ImreSamu 

I'm going to close out this issue, but it will still possible to add comments to it.
