### ISSUE TITLE
docker build ARM images dont run

### ISSUE THREAD

**Issue by liyin37** [postgis/docker-postgis#325]
https://github.com/postgis/docker-postgis/tree/master/12-3.3
when I docker build  successful in ARM server
I run this docker images，find  errors:
![image](https://user-images.githubusercontent.com/42507175/202952001-62bf0cbe-9f42-4929-9967-b2b4b0aecd3d.png)

**Comment by ImreSamu** [comment]
Thanks for posting this issue! 

Please use ["GitHub markdown - for Quoting code/logs"](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)
* "To format code or text into its own distinct block, use triple backticks."

> when I docker build successful in ARM server

interesting .. 

please share all your commands: 
* full  - docker build
  * example `docker build --pull -t postgis/postgis:12-3.3 12-3.3`  
     * The `--pull` is very important! 
        * `--pull`   "Always attempt to pull a newer version of the image"
        * https://stackoverflow.com/questions/58488535/whats-the-purpose-of-docker-build-pull

* and a minimal test code

And please share your other important info ( system, hardware )

Important:
* the repository uses: `VERSION=12-3.3 VARIANT=default make build` command to build the image.

**Comment by liyin37** [comment]
@

> Thanks for posting this issue!
> 
> Please use ["GitHub markdown - for Quoting code/logs"](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)
> 
> * "To format code or text into its own distinct block, use triple backticks."
> 
> > when I docker build successful in ARM server
> 
> interesting ..
> 
> please share all your commands:
> 
> * full  - docker build
>   
>   * example `docker build --pull -t postgis/postgis:12-3.3 12-3.3`
>     
>     * The `--pull` is very important!
>       
>       * `--pull`   "Always attempt to pull a newer version of the image"
>       * https://stackoverflow.com/questions/58488535/whats-the-purpose-of-docker-build-pull
> * and a minimal test code
> 
> And please share your other important info ( system, hardware )
> 
> Important:
> 
> * the repository uses: `VERSION=12-3.3 VARIANT=default make build` command to build the image.

thanks，but  when I use docker build --pull happen new errors

[root@geos docker-postgis]# cd 12-3.3/
[root@geos 12-3.3]# ls -l
total 16
drwxr-xr-x 2 root root 4096 Oct 15 09:11 alpine
-rw-r--r-- 1 root root  803 Oct 15 09:11 Dockerfile
-rwxr-xr-x 1 root root  731 Oct 15 09:11 initdb-postgis.sh
-rwxr-xr-x 1 root root 1045 Oct 15 09:11 update-postgis.sh
[root@geos 12-3.3]# docker build --pull -t postgis:12.3-3 .
![image](https://user-images.githubusercontent.com/42507175/203221371-58793e1e-44cf-4643-a588-54a127bef323.png)

**Comment by liyin37** [comment]
[root@geos ~]# uname -r
4.18.0-80.7.2.el7.aarch64
[root@geos ~]# uname -a
Linux geos 4.18.0-80.7.2.el7.aarch64 #1 SMP Thu Sep 12 16:13:20 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux

**Comment by liyin37** [comment]
@ImreSamu 
I rebuild it in new dockerfile，but I run error
![image](https://user-images.githubusercontent.com/42507175/203239620-1fd91dd9-a36c-4b61-a21b-a243df220ae4.png)
