### ISSUE TITLE
Update to alpine 3.17 

### ISSUE THREAD

**Issue by ImreSamu** [postgis/docker-postgis#328]
upstream docker Postgres image updated to alpine 3.17  https://github.com/docker-library/postgres/pull/1017
( so no upstream support for `alpine3.16` in the future.) 

todo :
- update `README.md`,  `Dockerfile.alpine.template`, `update.sh`
   - update 3.16 to 3.17 ( https://github.com/search?q=repo%3Apostgis%2Fdocker-postgis+3.16&type=code )
   
waiting for:  https://github.com/postgis/docker-postgis/pull/324

**Comment by phillipross** [comment]
PR #324 is now merged.  thanks!
