### ISSUE TITLE
3D function errors due to bug in sfcgal

### ISSUE THREAD

**Issue by Alexandre27** [postgis/docker-postgis#333]
When using the `postgis/postgis:15-3.3` I encountered the error in image below when using `ST_3DIntersects` and `ST_3DIntersection`.  
![image](https://user-images.githubusercontent.com/3704961/208888457-4857d8a2-4d2a-48a1-90b4-478ba76a5d94.png)

When a colleague ran the same query using a apt install in the ubuntu 22.10, everything ran without any errors, so after comparing the `postgis_full_version` output it seemed that it worked on sfcgal version 1.4.1, but the docker image has the 1.3.8.
Changing the `15-master` dockerfile to have the same versions as  `postgis/postgis:15-3.3` and installing cgal 5.3 and sfcgal 1.4.1 made the error disappear.

I think it's due to this [bug](https://gitlab.com/Oslandia/SFCGAL/-/issues/247) that was fixed in version 1.4.1. This is more of an FYI, as the version is limited by the base image package version. I'm also not sure if this is an issue to docker-postgis or to postgis, as you may also encounter this error without using docker.

**Comment by swiss-knight** [comment]
I'm having exactly the same problem. 

`libsfcgal1` is only available in version 1.3.x on the latest Debian stable whereas on Ubuntu 22.xx, it's available in version 1.4.x

Please support this discussion: https://github.com/postgis/docker-postgis/discussions/335

**Comment by ImreSamu** [comment]
**now (2023-03-18)**  
the `postgis/postgis:15-master`  version contains 
the latest sfcgal and the latest  cgal  [5.5.x-branch](https://github.com/CGAL/cgal/tree/5.5.x-branch) 
```
 POSTGIS="3.4.0dev 3.3.0rc2-686-g0a7d3bc20" [EXTENSION]
    PGSQL="150" 
    GEOS="3.12.0dev-CAPI-1.18.0" 
    SFCGAL="SFCGAL 1.4.1, CGAL 5.5.3, BOOST 1.74.0" 
    PROJ="9.3.0" 
    GDAL="GDAL 3.7.0dev-67eaa768c0, released 2023/03/18" 
    LIBXML="2.9.10" 
    LIBJSON="0.15" 
    LIBPROTOBUF="1.3.3" 
    WAGYU="0.5.0 (Internal)" 
    TOPOLOGY RASTER
 ```

**Comment by ImreSamu** [comment]
now the `postgis/postgis:15-master` == SFCGAL 1.5.0, CGAL 5.6.1

 ```
 2023-11-17T16:59:58.6091296Z #21 0.286 
PostgreSQL 15.5 (Debian 15.5-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
POSTGIS="3.5.0dev 3.4.0rc1-749-g42f04a29e" [EXTENSION] 
   PGSQL="150" GEOS="3.13.0dev-CAPI-1.18.0" 
   SFCGAL="SFCGAL 1.5.0, CGAL 5.6.1, BOOST 1.74.0" 
   PROJ="9.4.0 NETWORK_ENABLED=OFF URL_ENDPOINT=https://cdn.proj.org USER_WRITABLE_DIRECTORY=/var/lib/postgresql/.local/share/proj DATABASE_PATH=/usr/local/share/proj/proj.db" GDAL="GDAL 3.9.0dev-9a3e48a2cb, released 2023/11/06" 
   LIBXML="2.9.10" 
   LIBJSON="0.15" 
   LIBPROTOBUF="1.3.3" 
   WAGYU="0.5.0 (Internal)" 
   TOPOLOGY RASTER
```

I am closing this issue. If you have any new information related to this, please let me know, and I will reopen it.
