### ISSUE TITLE
#30 10.07 E: Version '3.3.2+dfsg-1.pgdg110+1' for 'postgresql-15-postgis-3' was not found

### ISSUE THREAD

**Issue by code-with-rashid** [postgis/docker-postgis#346]
#30 10.07 E: Version '3.3.2+dfsg-1.pgdg110+1' for 'postgresql-15-postgis-3' was not found

**Comment by ImreSamu** [comment]
Hi @code-with-rashid !

> Version '3.3.2+dfsg-1.pgdg110+1' for 'postgresql-15-postgis-3' was not found

Thanks for posting this issue!

Please verify with the latest version (the master has been updated approximately 17 hours ago):

* Now this patch is in the master:  
    *  https://github.com/postgis/docker-postgis/pull/344  
* And now, in this file: :  https://github.com/postgis/docker-postgis/blob/master/15-3.3/Dockerfile#L11_L12
   * `ENV POSTGIS_VERSION 3.3.3+dfsg-1~exp1.pgdg110+1`
* The Docker Postgis CI is also working fine:
    * https://github.com/postgis/docker-postgis/actions/runs/5135181737
