### ISSUE TITLE
Upgrade Postgres 15.5

### ISSUE THREAD

**Issue by mkinberger** [postgis/docker-postgis#365]
The containers 15-3.4 and 15-3.4-alpine still use the old postgres containers with postgres version 15.4. 
Postgres 15.5 is already used in the official postgres image. 
Why is this version not yet available in the postgis containers?
We would like to quickly update to postgres 15.5.

**Comment by ImreSamu** [comment]
> Why is this version not yet available in the postgis containers?


Although Postgres 15.5 was released last week (2023-11-09), 
the input for PostGIS images on `postgres:15` **was only generated two days ago,** 
as seen in https://github.com/docker-library/official-images/pull/15699 .
This caused it to miss the [usual Monday morning](https://github.com/postgis/docker-postgis/blob/ab6f2096b68fa9c4831044ab09a680f771ca61b3/.github/workflows/main.yml#L7)  weekly update of docker-postgis.

However, I understand the problem and will try to update the PostGIS Docker images before the next Monday's update.

**Comment by ImreSamu** [comment]
I have created a basic Update Pull Request, which will update every PostGIS image.
https://github.com/postgis/docker-postgis/pull/366

**Comment by ImreSamu** [comment]
I have successfully rerun the weekly image generation CI, 
and the postgis images are now based on `PostgreSQL 15.5`.

I am closing this issue. If you have any new information related to this, please let me know, and I will reopen it.
